name: InsaneSEO
favicon: null
layout_spectrum: 0.39078556140884757
typography_spectrum: 0.5968930623494089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211d72'
    - '#686868'
    - '#929292'
    - '#c6c6c6'
  brandStrength: 0.9375
  lightness: 0.3526040930300951
  saturation: 0.3078577849082649
  rhythmicContrast: 0.1195662054233253
purpose: []
